config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users, controllers: {
    registrations: "devise/custom_registrations"
  }
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name,    presence: true
  validates :address, presence: true
  validates :phone,   presence: true
  validates :role,    presence: true,
                      inclusion: { in: %w(company veterinary) }

  validates :cnpj,    presence: true, cnpj: true, if: 'role == "company"'
  validates :crmv,    presence: true,
                      numericality: { only_integer: true },
                      length: { maximum: 5 }, if: 'role == "veterinary"'

  before_validation :ensure_role

  private
  def ensure_role
    self.role = 'company' if role.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Usuários Cadastrados', users_path %></li>
  <li><%= link_to 'Editar conta', edit_user_registration_path %></li>
  <li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Entrar', new_user_session_path %></li>
  <li><%= link_to 'Cadastrar: Sou Veterinário', new_user_registration_path(role: 'veterinary') %></li>
  <li><%= link_to 'Cadastrar: Sou Empresa', new_user_registration_path(role: 'company') %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Sobre', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>Sobre<% end %>
<h3>Sobre o projeto</h3>
<p>
Teste feito para Vaga da <a href="www.petbooking.com.br">Petbooking</a>
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user if user.name %></td>
<td><%= link_to user.address, user if user.address %></td>
<td><%= link_to user.phone, user if user.phone %></td>
<td><%= link_to user.cnpj, user if user.cnpj %></td>
<td><%= link_to user.crmv, user if user.crmv %></td>
<td><%= link_to user.role, user if user.role %></td>
<td><%= link_to user.email, user if user.email %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Usuários</h3>
    <div class="column">
      <table class="table">
        <thead>
            <th>Nome</th>
            <th>Endereço</th>
            <th>Telefone</th>
            <th>CNPJ</th>
            <th>CRMV</th>
            <th>Tipo</th>
            <th>E-mail</th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>Usuário cadastrado</h3>
<p><b>Nome:</b> <%= @user.name if @user.name %></p>
<p><b>Endereço:</b> <%= @user.address if @user.address %></p>
<p><b>Telefone:</b> <%= @user.phone if @user.phone %></p>
<p><b>CNPJ:</b> <%= @user.cnpj if @user.cnpj %></p>
<p><b>CRMV:</b> <%= @user.crmv if @user.crmv %></p>
<p><b>Tipo:</b> <%= @user.role if @user.role %></p>
<p><b>Email:</b> <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Petbooking</h3>
<p><%= link_to 'Usuários:', users_path %> <%= User.count %> registrado</p>